version: "2"

services:
    db:
        image: amd64/postgres:10-alpine
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        expose:
            - "5432"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=DO$od~lBd}8L

    artemis:
        image: vromero/activemq-artemis:2.6.3-alpine
        volumes:
            - ./artemis/:/var/lib/artemis/etc-override/
        expose:
            - "61616"
        ports:
            - 8161:8161
            - 61616:61616
        environment:
            - ARTEMIS_USERNAME=angio_app
            - ARTEMIS_PASSWORD=q1w2e3

    analyse-executor:
        image: analyse-executor:latest
        build:
            context: ./
            dockerfile: ./analyse-executor/src/main/docker/Dockerfile
        volumes:
            - static-content:/opt/analyse-executor/static
        tty: true
        depends_on:
            - db
            - artemis

volumes:
    static-content:
        driver_opts:
            type: none
            device: ${PWD}/angio-backend/src/main/resources/static
            o: bind
