version: "2"

services:
    db:
        image: amd64/postgres:10-alpine
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d
        expose:
            - "5432"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=DO$od~lBd}8L

volumes:
    static-content:
        driver_opts:
            type: none
            device: ${PWD}/angio-backend/src/main/resources/static
            o: bind
