version: "2"

services:
    angio-backend:
        image: angio-backend:latest
        build:
            context: ./angio-backend
            dockerfile: ./src/main/docker/Dockerfile
        volumes:
            - ~/.m2:/root/.m2:rw # Maven repository files
            - static-content:/angio-backend/src/main/resources/static
        ports:
            - 8000:8000 # Port for remote debug
            - 8080:8080
        tty: true
        depends_on:
            - db
            - artemis
