version: "2"

services:
    artemis:
        image: vromero/activemq-artemis:2.6.3-alpine
        volumes:
            - ./artemis/:/var/lib/artemis/etc-override/
        expose:
            - "61616"
        ports:
            - 8161:8161
            - 61616:61616
        env_file:
            - .artemis.env

    analyse-executor:
        image: analyse-executor:latest
        build:
            context: ./
            dockerfile: ./analyse-executor/src/main/docker/Dockerfile
        volumes:
            - static-content:/opt/analyse-executor/static
        tty: true
        depends_on:
            - db
            - artemis
        env_file:
            - .db.env
            - .artemis.env
