version: "2"

services:
    db:
        image: postgres:10
        volumes:
            - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        expose:
            - "5432"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=DO$od~lBd}8L

    server:
        build: ./server
        volumes:
            - ~/.m2:/root/.m2:rw # Maven repository files
            - ./server:/server
        ports:
            - 8000:8000 # Port for remote debug
            - 80:80
        command: mvn clean spring-boot:run
        working_dir: /server
        depends_on:
            - db
  
