spring:
    main:
        web-application-type: none

    artemis:
        mode: native
        host: artemis
        port: 61616
        user: angio_app
        password: q1w2e3

analyseexecutor:
        app:
            upload-directory: src/main/resources/static/uploads/
            result-image-format: png

            jms:
                analyse-to-execute-queue: analyseToExecute
                analyse-results-queue: analyseResults