spring:
    artemis:
        host: artemis
        password: ${ARTEMIS_PASSWORD}

    datasource:
        url: jdbc:postgresql://db:5432/angio_app_db
        username: angio_app
        password: ${ANGIO_DB_USER_PASSWORD}
        driver-class-name: org.postgresql.Driver

analyseexecutor:
    app:
        upload-directory: /opt/analyse-executor/static/uploads
