spring:
    main:
        web-application-type: none

    artemis:
        mode: native
        host: localhost
        port: 61616
        user: angio_app
        password: q1w2e3

    datasource:
        url: jdbc:postgresql://localhost:5432/angio_app_db
        username: angio_app
        password: q1w2e3
        driver-class-name: org.postgresql.Driver

analyseexecutor:
    app:
        upload-directory: analyse-executor/src/main/resources/static/uploads/
        result-image-format: png

        jms:
            analyse-to-execute-queue: queue.analyse.toExecute
            analyse-results-queue: queue.analyse.results