server:
    port: 80

spring:
    jpa:
        hibernate:
            ddl-auto: validate

    jackson:
        serialization:
            INDENT_OUTPUT: true

    datasource:
        url: jdbc:postgresql://db:5432/angio_app_db
        username: angio_app
        password: q1w2e3
        driver-class-name: org.postgresql.Driver


    mail:
        host: smtp.mail.ru
        port: 465
        username: angiovision.team@mail.ru
        password: q1w2e3r4%
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

angio:
    app:
        jwt:
            header: Authorization
            token-type: Bearer
            secret: \\xd7H\\xb2\\xa6\\xf0y\\xb9\\xdd\\x1c\\xd6q\\xd6\\xd0\\x1ck\\xe0}\\x02\\x85\\x04\\xe7\\xd4\\xed=
            expiration: 2592000
        analyse-images-directory: ./static/images/analyses

liquibase:
    change-log: classpath:db/liquibase/master.yml
