spring:

    artemis:
        mode: native
        host: artemis
        port: 61616
        user: angio_app
        password: q1w2e3

    datasource:
        url: jdbc:postgresql://db:5432/angio_app_db
        username: angio_app
        password: q1w2e3
        driver-class-name: org.postgresql.Driver