spring:

    artemis:
        host: artemis
        password: ${ARTEMIS_PASSWORD}

    datasource:
        url: jdbc:postgresql://db:5432/angio_app_db?reWriteBatchedInserts=true
        password: ${ANGIO_DB_USER_PASSWORD}

logging:
    level:
        root: WARN
        com.angio.angiobackend: ${ANGIO_LOG_MODE}
        org.springframework.web: INFO
        org.springframework.security: INFO
        org.hibernate.stat: OFF
        org.hibernate.SQL: OFF
        org.hibernate.type: OFF
        org.hibernate.cache: OFF

angiobackend:
    app:
        base-url: ${BASE_URL}
        sent-email-directory: /opt/angio-backend/static/email
        upload-directory: /opt/angio-backend/static/uploads/
        frontend-dist-directory: /opt/angio-backend/static/dist/
