server:
    port: 8080
    error:
        whitelabel:
            enabled: false

spring:
    jpa:
        hibernate:
            ddl-auto: validate
            format-sql: true
        open-in-view: false
        show-sql: true


    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB


    jackson:
        serialization:
            indent_output: true
        default-property-inclusion: non_null
        time-zone: Europe/Samara
        date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

    artemis:
        mode: native
        host: localhost
        port: 61616
        user: angio_app
        password: q1w2e3

    datasource:
        url: jdbc:postgresql://localhost:5432/angio_app_db
        username: angio_app
        password: q1w2e3
        driver-class-name: org.postgresql.Driver

    mail:
        host: smtp.mail.ru
        port: 465
        username: angiovision.team@mail.ru
        password: q1w2e3r4%
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    liquibase:
        change-log: classpath:db/liquibase/master.yml

    mvc:
        throw-exception-if-no-handler-found: true

    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration


logging:
    level:
        root: WARN
        com.angio.angiobackend: INFO
        org.springframework.web: DEBUG
        org.springframework.security: INFO

angio:
    app:
        upload-directory: src/main/resources/static/uploads/
        upload-path: static/uploads/
        image-upload-extensions:
            - bmp
            - png
        document-upload-extensions:
            - pdf

        jms:
            analyse-to-execute-queue: queue.analyse.toExecute
            analyse-results-queue: queue.analyse.results

        scheduling:
            # every day at 3:00
            purge-analyses-period: 0 0 3 * * *